let app=document.getElementById("app");
let playerCards=[], botCards=[], botNames=[], currentPlayer=0, totalPlayers=2, coins=500, score=0, teamMode=false;
const names=["Emma","Sophia","Mia","Olivia","Ava","Lily","Chloe","Zoe","Grace","Maya","Ella","Nora","Ivy","Ruby","Aria","Isla","Amelia","Hannah"];
const colors=["red","blue","yellow","green"], colorNames=["Red","Blue","Yellow","Green"];
function save(){localStorage.setItem("ccb",JSON.stringify({coins,score}))}
function load(){let d=JSON.parse(localStorage.getItem("ccb")||"{}");coins=d.coins??500;score=d.score??0}
function home(){load();app.innerHTML=`<h1>🎮 Color Card Battle</h1><p class="tagline">Fast card battle with friends-style auto players</p><div class="panel"><b>Coins:</b> ${coins} 🪙 | <b>Score:</b> ${score}</div><div class="menu"><button onclick="selectMode(false)">Solo / Auto Players</button><button onclick="selectMode(true)">Team Mode 2v2 / 3v3</button><button onclick="onlineDemo()" class="blueBtn">Online Match</button><button onclick="friends()">Friends</button><button onclick="shop()" class="goldBtn">Shop</button><button onclick="settings()">Settings</button></div><p class="small">Upload-ready demo version: offline bots, 2–6 players, team display, shop, coins.</p>`}
function selectMode(team){teamMode=team;app.innerHTML=`<h1>${team?'🤝 Team Mode':'🎮 Select Players'}</h1><div class="menu"><button onclick="startGame(2)">2 Players</button><button onclick="startGame(3)">3 Players</button><button onclick="startGame(4)">4 Players</button><button onclick="startGame(5)">5 Players</button><button onclick="startGame(6)">6 Players</button><button onclick="home()" class="danger">Back</button></div>`}
function randomCard(){let c=Math.floor(Math.random()*4), n=Math.floor(Math.random()*9)+1;return {text:colorNames[c]+" "+n,color:colors[c],num:n}}
function specialCard(){let c=Math.floor(Math.random()*4);let specials=["Skip","Draw +2","Reverse"];let s=specials[Math.floor(Math.random()*specials.length)];return {text:colorNames[c]+" "+s,color:colors[c],num:s}}
function getCard(){return Math.random()<0.22?specialCard():randomCard()}
function startGame(players){totalPlayers=players;currentPlayer=0;playerCards=[];botCards=[];botNames=[];for(let i=0;i<7;i++)playerCards.push(getCard());for(let b=0;b<players-1;b++){botNames.push(names[b]);let hand=[];for(let i=0;i<7;i++)hand.push(getCard());botCards.push(hand)}let c=getCard();app.innerHTML=`<h1>🎮 Battle Started</h1><p id="modeText">${players} Players ${teamMode?'Team Match':'Solo Match'}</p><div id="playersBox" class="players-box"></div><h2 id="turnText">Your Turn</h2><div class="panel"><p class="info">Coins: <span id="coins">${coins}</span> 🪙 | Score: <span id="score">${score}</span></p><p id="counts" class="small"></p></div><h2>Current Card</h2><div class="hand"><div id="currentCard" data-color="${c.color}" data-num="${c.num}" class="card ${c.color}">${c.text}</div></div><h2>Your Cards</h2><div id="playerHand" class="hand"></div><button onclick="drawCard()">Draw Card</button><button onclick="home()" class="danger">Exit</button>`;render()}
function render(){let box=document.getElementById("playersBox");let html=`<div class="player-chip ${currentPlayer===0?'active':''}">🧑 You ${teamMode?'A':''}</div>`;botNames.forEach((n,i)=>{let team=teamMode?(i%2===0?'B':'A'):'';html+=`<div class="player-chip ${currentPlayer===i+1?'active':''}">👩 ${n} ${team}</div>`});box.innerHTML=html;let hand=document.getElementById("playerHand");hand.innerHTML="";playerCards.forEach((c,i)=>hand.innerHTML+=`<div class="card ${c.color}" onclick="playCard(${i})">${c.text}</div>`);let text=`You: ${playerCards.length} cards | `;botNames.forEach((n,i)=>text+=`${n}: ${botCards[i].length} | `);document.getElementById("counts").innerHTML=text}
function isValid(c){let cur=document.getElementById("currentCard");return c.color===cur.dataset.color || c.num==cur.dataset.num || c.num==="Draw +2"}
function setCurrent(c){let cur=document.getElementById("currentCard");cur.innerHTML=c.text;cur.className="card "+c.color;cur.dataset.color=c.color;cur.dataset.num=c.num}
function playCard(i){if(currentPlayer!==0)return;let c=playerCards[i];if(!isValid(c)){alert("❌ Same colour or same number only!");return}setCurrent(c);playerCards.splice(i,1);score+=10;coins+=5;save();if(c.num==="Draw +2"&&botCards[0]){botCards[0].push(getCard(),getCard())}if(playerCards.length===0)return win("🎉 You Win! +100 coins",true);nextTurn()}
function nextTurn(){currentPlayer++;if(currentPlayer>=totalPlayers)currentPlayer=0;render();if(currentPlayer===0){document.getElementById("turnText").innerHTML="Your Turn";return}document.getElementById("turnText").innerHTML=botNames[currentPlayer-1]+"'s Turn";setTimeout(botTurn,900)}
function botTurn(){let hand=botCards[currentPlayer-1];let idx=hand.findIndex(isValid);if(idx===-1){hand.push(getCard())}else{let c=hand[idx];setCurrent(c);hand.splice(idx,1);if(c.num==="Draw +2")playerCards.push(getCard(),getCard())}if(hand.length===0)return win("👩 "+botNames[currentPlayer-1]+" Wins!",false);nextTurn()}
function drawCard(){if(currentPlayer!==0)return;playerCards.push(getCard());nextTurn()}
function win(msg,you){if(you){coins+=100;score+=100;save()}alert(msg);home()}
function onlineDemo(){app.innerHTML=`<h1>🌍 Online Match</h1><div class="panel"><p>Online real multiplayer needs Firebase/Photon server later.</p><p>This demo fills empty seats with human-style names and avatars.</p></div><button onclick="selectMode(false)">Play Demo Match</button><button onclick="home()" class="danger">Back</button>`}
function friends(){app.innerHTML=`<h1>👥 Friends</h1><div class="panel"><p>Emma ✅ Online</p><p>Sophia ✅ Online</p><p>Mia 🕒 Last seen recently</p></div><button onclick="alert('Friend request sent!')">Add Random Friend</button><button onclick="home()" class="danger">Back</button>`}
function shop(){app.innerHTML=`<h1>🛒 Shop</h1><p>Coins: ${coins} 🪙</p><div class="shop-item"><span>Gold Card Skin</span><button onclick="buy(200)">200</button></div><div class="shop-item"><span>Premium Avatar</span><button onclick="buy(300)">300</button></div><button onclick="home()" class="danger">Back</button>`}
function buy(price){if(coins>=price){coins-=price;save();alert('Purchased ✅');shop()}else alert('Not enough coins ❌')}
function settings(){app.innerHTML=`<h1>⚙️ Settings</h1><button onclick="localStorage.removeItem('ccb');coins=500;score=0;home()">Reset Progress</button><button onclick="home()" class="danger">Back</button>`}
home();